// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
///
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4CHhnqxqquDqnW0hlNXXtVdVTAxMXqM',
    appId: '1:741236385874:web:9b293d6cc53a648b75978b',
    messagingSenderId: '741236385874',
    projectId: 'parcelfyp',
    authDomain: 'parcelfyp.firebaseapp.com',
    storageBucket: 'parcelfyp.appspot.com',
    measurementId: 'G-DJTYLG79JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5rQbodUEfd93sYnPArjZPqGdzrnfOxu0',
    appId: '1:741236385874:android:45c39ffe03beb75075978b',
    messagingSenderId: '741236385874',
    projectId: 'parcelfyp',
    storageBucket: 'parcelfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVVwILb2wvwWXc56IMCVbUZYieBh5DPw4',
    appId: '1:741236385874:ios:d248e50897edf03175978b',
    messagingSenderId: '741236385874',
    projectId: 'parcelfyp',
    storageBucket: 'parcelfyp.appspot.com',
    iosBundleId: 'com.example.parcelmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVVwILb2wvwWXc56IMCVbUZYieBh5DPw4',
    appId: '1:741236385874:ios:9f894b2f5802f18075978b',
    messagingSenderId: '741236385874',
    projectId: 'parcelfyp',
    storageBucket: 'parcelfyp.appspot.com',
    iosBundleId: 'com.example.parcelmanagement.RunnerTests',
  );
}
